### ISSUE TITLE
Does not work when screen is off

### ISSUE THREAD

**Issue by gadgetreviews** [arekolek/simple-phone#11]
I managed to write a code to replace default phone app as explained in this repository. It is working only when screen is turned on. If screen is turned off, I can only hear ring tone, screen does not turn on. If I turn on screen manually, I can't see any call interface (not mine or not system default phone app. So I can't handle answer that call). How can I turn on screen when phone rings? I've tried several solutions about how to turn on screen, but no one is working in this case.

Any suggestions?

**Comment by arekolek** [comment]
You can take a look at https://github.com/arekolek/simple-phone/issues/1
