### ISSUE TITLE
Question: is it possible to show the built in during-call-UI, from this one?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [arekolek/simple-phone#2]
There are tons of functions that are available for when you have the control here, of the during-call-UI.

Is it possible, since a developer might not implement&use all of them, to revert back to the built-in-UI ? 

For example, suppose I create an app based on this sample, that only offers to answer and reject calls.

This means I didn't handle conference calls, video calls, etc... 

Is there an API of some sort, that allows me to put a button on the UI, to go back to the built-in-UI ? One that has everything else covered?

Or once I replace the UI, I have to implement it all? Meaning all or nothing?

**Comment by AndroidDeveloperLB** [comment]
Since I couldn't find an answer to this, I've decided to write a request for it:
https://issuetracker.google.com/issues/110862208
And something similar here:
https://issuetracker.google.com/issues/110894922

**Comment by arekolek** [comment]
I'm not sure if there's an API that allows you to revert to built in UI. What I know is that if your custom phone app crashes during a call, the built-in UI takes over. But that's probably not the best solution... :P

**Comment by AndroidDeveloperLB** [comment]
Hmmm... What if you used the non-recommended call to `System.exit` ?

**Comment by AndroidDeveloperLB** [comment]
close and mark as question?
