### ISSUE TITLE
CallService not invoking in xiaomi devices.

### ISSUE THREAD

**Issue by girubhai** [arekolek/simple-phone#9]
**Describe the bug**

I wanted to call from the app and when I clicked the number I want to call, I got redirected to my phone default caller.

To Reproduce

1. Open the app
2. Pick any number and dial.
3. Note the issue

I debug the app and notice that CallService not invoking.

**Device Details**

- SDK:23,
- Brand:Xiaomi,
- Model:Redmi 3S

**Comment by arekolek** [comment]
Thanks for the report.

After step 1. shouldn't the app ask you to set is as default Phone app?

![image](https://user-images.githubusercontent.com/893533/62766677-50cbc080-ba93-11e9-9718-66678f90aa83.png)

If it's not set as default, CallService won't be notified about calls.

It might be a problem with the particular device, but I don't have access to that model, so I can only rely on what you can tell me. Maybe you can attach the logs from Logcat to this issue and they would shed some light on the problem.

**Comment by girubhai** [comment]
@arekolek thanks to reply.

It shows popup to set default app and also it got default. But the problem is that after entering number it doesn't show calling screen of this app instead it shows default phone dial screen i.e. **InCallUI**  shows calling screen of phone.

I did verify that on other devices it invoke to `CallService class` during call then `CallActivity` class start. but in xiaomi device it didn't invoke `CallService class` hence `CallActivity` not started.

**Comment by RijoshEnfin** [comment]
any soution in  xiaomi devices

**Comment by antonyhayek** [comment]
I am having same issue on some Xiaomi Devices not all of them. the InCallService ain't getting invoked. Any help please?

**Comment by power76** [comment]
Yes, I got the same issue on Nubia Z17. I guessed it maybe came from the default only worked on Dial not Call UI. Cause I noticed that in App info settings, I could set the "phone" default to simple-phone but not "Call" where only be the system default.

**Comment by power76** [comment]
By the way, it work well on Simulator. So I think the phone vendor maybe revised something.

**Comment by arekolek** [comment]
@girubhai @RijoshEnfin @antonyhayek @power76 did you try reporting this issue to Xiaomi? I guess it should be easy given that you can use this project as a Minimum Verifiable Example that they can use to reproduce the issue

Not sure where you can report it, maybe there is some "Report bug" option in the system settings or some other manufacturer app

**Comment by power76** [comment]
> @girubhai @RijoshEnfin @antonyhayek @power76 did you try reporting this issue to Xiaomi? I guess it should be easy given that you can use this project as a Minimum Verifiable Example that they can use to reproduce the issue
> 
> Not sure where you can report it, maybe there is some "Report bug" option in the system settings or some other manufacturer app

hi, arekolek
Thanks for your reply. And the phone I used is made by Nubia not Xiaomi. And I have tried to add an Intent filter into the AndroidManifest.xml as below:
`<intent-filter>
                <action android:name="android.intent.action.DIAL" />
                <action android:name="android.intent.action.CALL" />
                <category android:name="android.intent.category.DEFAULT" />
 </intent-filter>`


Then it can be setting default in Phone and Call app setting. But cannot work well.
